#!/bin/sh
#
# Check that the code follows a consistent code style
#

indentoptions="-npro -kr -i8 -ts8 -sob -l80 -ss -ncs -cp1 -il0"

echo "--Checking style--"
files=$(git diff-index --name-only --diff-filter=AM HEAD | grep -E '\.[ch](pp)?$')
indent $indentoptions $files 2> /dev/null
for file in $files
do
	if ! diff -u ${file}~ ${file}; then
		changedfiles="$changedfiles $file"
	fi
	rm -f ${file}~
done
if [ $changedfiles ]; then
	echo "Code style error in $changedfiles"
	echo "The files have been reindent by GNU indent, see above diff output"
	echo "Please review and run 'git add $changedfiles && git commit'"
	exit 1
fi
echo "--Checking style pass--"
